theme = "tokyonight_custom"

[editor]
color-modes = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator"
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = false

[editor.soft-wrap]
enable = true

[keys.normal]
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]
C-y = ":sh wezterm cli split-pane --left --percent 40 -- ~/.config/helix/wezilix.sh $WEZTERM_PANE open > /dev/null"
