[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # status line
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ }
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo = 'houtsnip/vim-emacscommandline'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
    let g:syntastic_enable_signs=1
    let g:syntastic_auto_loc_list=2
    let g:syntastic_go_checkers = ['golint', 'gotype', 'govet', 'go']
'''

[[plugins]] # completion
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = 'context_filetype.vim'
#on_event = 'InsertEnter'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1
    let g:deoplete#enable_smart_case = 1

    " <CR>: close popup
    inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"

    " automatically closing the scratch window.
    autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'

# Lang
[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
    let g:go_fmt_command = 'goimports'
    let s:goargs = go#package#ImportPath(expand('%:p:h'))
    let g:neomake_go_errcheck_maker = {
        \ 'args': ['-abspath', s:goargs],
        \ 'append_file': 0,
        \ 'errorformat': '%f:%l:%c:\ %m, %f:%l:%c\ %#%m',
        \ }
    let g:neomake_go_enabled_makers = ['golint', 'govet', 'errcheck']
    let g:go_template_autocreate = 0
'''

[[plugins]]
repo = 'ryym/vim-riot'

[[plugins]]
repo = 'leafgarland/typescript-vim'

# Colorscheme
[[plugins]]
repo = 'tomasr/molokai'
